### ISSUE TITLE
Syn is not defined

### ISSUE THREAD

**Issue by verzola** [minkphp/MinkSelenium2Driver#191] opened 2014-12-17 15:55 UTC
I'm trying to integrate Behat and Mink with Selenium Hub, and when I try to run the tests, o got this error:

![screenshot from 2014-12-17 13 50 58](https://cloud.githubusercontent.com/assets/2985522/5473914/38be6e94-85f4-11e4-8e78-11cda18cf6e9.png)

I found that Syn is a JS Library (I've read http://bitovi.com/blog/2010/07/syn-a-standalone-synthetic-event-library.html). Is that something new or what? Do I have to update the Selenium version to make it work? Thanks!

**Comment by MaxQA** [comment] 2015-07-14 14:08
Meeting same issue. Trying login to Facebook. Since one week or so. Was working before.

**Comment by aik099** [comment] 2015-07-14 20:05
@verzola , the link in https://github.com/minkphp/MinkSelenium2Driver/issues/191#issuecomment-67624224 comment is dead. Please use Gist instead because it surely won't expire.

@MaxQA , if you can reproduce the issue maybe you can attach some detail debug output as requested in https://github.com/minkphp/MinkSelenium2Driver/issues/191#issuecomment-67476225 ?

**Comment by stof** [comment] 2017-01-03 17:30
Closing as no additional details have been provided in 1.5 year

**Closed by stof** 2017-01-03 17:30 UTC
Labels: response-needed
